Repository Computational-Puzzles/ComputationalPuzzles, pull requests merged in 2021-12, with the labels that each got.

#4 Configure jestjs
  jest.config.js
  jest.setup.ts
  package-lock.json
  package.json
  src/__tests__/pages/index.ts
  src/__tests__/services/index.ts
  src/__tests__/utils/index.ts
  src/components/App/Example/Example.module.scss
  src/components/App/Example/Example.test.tsx
  src/components/App/Example/index.tsx
Labels: enhancement

#53 Add 404 page
  src/components/Global/ErrorDisplay/ErrorDisplay.module.scss
  src/components/Global/ErrorDisplay/index.tsx
  src/components/Global/index.tsx
  src/pages/error/404.tsx
Labels: enhancement

#60 Centralize types
  src/__tests__/pages/index.ts
  src/__tests__/services/index.ts
  src/__tests__/utils/index.ts
  src/components/App/CardGrid/index.tsx
  src/components/App/CardList/index.tsx
  src/components/Global/Button/index.tsx
  src/components/Global/Card/index.tsx
  src/components/Global/Header/index.tsx
  src/components/Global/Input/Input.module.scss
  src/components/Global/Input/index.tsx
  src/components/Global/Logo/index.tsx
  src/pages/api/auth/reset-password.ts
  src/pages/api/auth/signup.ts
  src/services/resetPassword.ts
  src/services/signup.ts
  src/types/api/auth/reset-password.ts
  src/types/api/auth/sign-up.ts
  src/types/button.ts
  src/types/cards.ts
  src/types/global.ts
Labels: enhancement

#63 Merge demo + link button
  src/components/Global/Button/Button.module.scss
  src/components/Global/Button/index.tsx
  src/components/Global/Card/index.tsx
  src/components/Global/Header/Header.module.scss
  src/components/Global/Header/index.tsx
  src/components/Global/Logo/index.tsx
  src/components/Global/index.tsx
  src/components/Product/Footer/index.tsx
  src/components/Product/Header/index.tsx
  src/components/Product/LandingContent/index.tsx
  src/styles/abstracts/_mixins/layout.scss
  src/styles/pages/Product.module.scss
  src/types/button.ts
  src/types/cards.ts
  src/types/global.ts
Labels: enhancement

#40 Puzzle page
  .babelrc
  package-lock.json
  package.json
  prisma/schema.prisma
  public/puzzleImages/test.jpg
  src/components/App/PuzzleInput/PuzzleInput.module.scss
  src/components/App/PuzzleInput/index.tsx
  src/components/Global/Header/index.tsx
  src/pages/api/puzzles/instances/[instanceId]/index.ts
  src/pages/api/puzzles/instances/index.ts
  src/pages/api/puzzles/instances/submit.ts
  src/pages/puzzles/[id].tsx
  src/pages/puzzles/[instanceId]/index.tsx
  src/services/puzzleInstance.ts
  src/styles/pages/PuzzlePage.module.scss
  src/types/api/puzzles/instances/puzzleInstance.ts
  src/types/api/puzzles/puzzle.ts
  src/types/api/puzzles/submission.ts
  src/types/global.ts
  src/utils/puzzles.ts
Labels: enhancement

#52 Add admin page with automatic QR
  package-lock.json
  src/components/App/QRGenerator/QRGenerator.module.scss
  src/components/App/QRGenerator/index.tsx
  src/components/App/index.tsx
  src/components/Global/ErrorDisplay/ErrorDisplay.module.scss
  src/components/Global/ErrorDisplay/index.tsx
  src/pages/403.tsx
  src/pages/404.tsx
  src/pages/500.tsx
  src/pages/admin/index.tsx
  src/pages/api/admin/validate.ts
  src/pages/api/user/index.ts
  src/services/admin.ts
Labels: enhancement

#68 Use built-in logo 'link' prop functionality
  src/components/Global/ErrorDisplay/index.tsx
Labels: enhancement

#67 Fix input component
  package-lock.json
  src/components/Global/Input/Input.module.scss
  src/components/Global/Input/index.tsx
  src/types/global.ts
Labels: bug

#39 Filter component
  src/components/Global/Filter/Filter.module.scss
  src/components/Global/Filter/index.tsx
  src/components/Global/RadioButton/RadioButton.module.scss
  src/components/Global/RadioButton/index.tsx
  src/components/Global/index.tsx
  src/pages/auth/login.tsx
Labels: enhancement

#72 Regeneralize types and prettify
  src/components/App/PuzzleInput/index.tsx
  src/components/Global/Filter/index.tsx
  src/components/Global/RadioButton/index.tsx
  src/components/Global/index.tsx
  src/pages/500.tsx
  src/types/cards.ts
  src/types/filter.ts
  src/types/global.ts
  src/types/puzzle.ts
  src/types/radioButton.ts
Labels: bug, enhancement

#70 Puzzle Page 404 Redirect
  src/pages/api/puzzles/instances/[instanceId]/index.ts
  src/pages/puzzles/[instanceId]/index.tsx
  src/services/puzzleInstance.ts
Labels: enhancement

#75 Puzzle Page Permissions
  src/components/App/index.tsx
  src/components/Global/LogStatusButton/index.tsx
  src/components/Global/RadioButton/index.tsx
  src/components/Global/index.tsx
  src/components/Product/Header/index.tsx
  src/pages/auth/login/index.tsx
  src/pages/puzzles/[instanceId]/index.tsx
  src/services/index.ts
  src/services/puzzleInstance.ts
  src/types/error.ts
  src/utils/error.ts
  src/utils/password.ts
  src/utils/puzzles.ts
Labels: enhancement

#79 Search and filter component
  src/components/Global/SearchAndFilter/SearchAndFilter.module.scss
  src/components/Global/SearchAndFilter/index.tsx
  src/components/Global/index.tsx
  src/types/searchAndFilter.ts
Labels: enhancement

#64 Map Renderer Functionality
  next.config.js
  package-lock.json
  package.json
  src/components/App/CardList/CardList.module.scss
  src/components/App/CardList/index.tsx
  src/components/App/MapGeocoder/MapGeocoder.module.scss
  src/components/App/MapGeocoder/index.tsx
  src/components/App/MapRenderer/MapRenderer.module.scss
  src/components/App/MapRenderer/index.tsx
  src/components/App/QRGenerator/index.tsx
  src/components/App/index.tsx
  src/components/Global/Card/Card.module.scss
  src/components/Global/Card/index.tsx
  src/components/Global/Filter/index.tsx
  src/components/Global/RadioButton/RadioButton.module.scss
  src/components/Global/RadioButton/index.tsx
  src/pages/api/puzzles/[id].tsx
  src/pages/api/puzzles/index.tsx
  src/pages/api/puzzles/instances/index.ts
  src/pages/puzzles/map/index.tsx
  src/services/puzzleInstance.ts
  src/styles/pages/PuzzleMap.module.scss
  src/types/button.ts
  src/types/cards.ts
  src/types/global.ts
  src/types/radioButton.ts
Labels: enhancement

#77 Puzzle page feedback
  public/feedbackGifs/correct/0.gif
  public/feedbackGifs/correct/1.gif
  public/feedbackGifs/correct/3.gif
  public/feedbackGifs/incorrect/0.gif
  public/feedbackGifs/incorrect/1.gif
  public/feedbackGifs/incorrect/2.gif
  src/components/App/FeedbackGif/FeedbackGif.module.scss
  src/components/App/FeedbackGif/index.tsx
  src/components/App/index.tsx
  src/pages/puzzles/[instanceId]/index.tsx
  src/services/feedbackGif.ts
  src/types/feedbackGif.ts
  src/utils/feedbackGif.ts
Labels: enhancement

#84 Puzzle list page
  src/components/Global/SearchAndFilter/index.tsx
  src/pages/puzzles/index.tsx
  src/styles/pages/PuzzleList.module.scss
Labels: enhancement

#73 Generate puzzle instance
  package-lock.json
  package.json
  prisma/schema.prisma
  src/components/App/PuzzleGenerate/PuzzleGenerate.module.scss
  src/components/App/PuzzleGenerate/index.tsx
  src/components/App/QRGenerator/QRGenerator.module.scss
  src/components/App/QRGenerator/index.tsx
  src/components/App/index.tsx
  src/components/Global/Header/Header.module.scss
  src/components/Global/Header/index.tsx
  src/components/Global/Input/index.tsx
  src/pages/admin/index.tsx
  src/pages/api/puzzles/instances/create.ts
  src/pages/puzzles/index.tsx
  src/services/index.ts
  src/services/puzzle.ts
  src/services/puzzleInstance.ts
  src/styles/pages/admin.module.scss
Labels: enhancement
